name: 🐛 Bug Report + Debugging
description: Report a bug and request Claude AI debugging assistance
title: "[BUG] "
labels: ["bug", "debugging", "claude-ai"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report with Claude AI Debugging

        Report a bug and get Claude AI assistance with systematic debugging.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: debugging-prompt
    attributes:
      label: Claude Debugging Prompt
      description: "Use the debugging prompt from `.github/prompts/development/debugging.md`"
      value: |
        Copy the debugging prompt and provide the error details, stack traces, and any relevant code.
